# Numpy 

Earlier Numpy was not available in python.<br>
Numpy was extracted from matlab, which was used for image processing.<br>
we use list, but as a data scientist we do not use array, we use numpy. 

In [1]:
import numpy as np 

#### Create an Array

In [2]:
np.array([1,2,3,4,5]) 

array([1, 2, 3, 4, 5])

In [3]:
type(np.array([1,2,3,4,5])) 

numpy.ndarray

#### upcasting of datatypes

In [4]:
np.array([1,2,3,4,5,"shudh"]) ## 1-d array

array(['1', '2', '3', '4', '5', 'shudh'], dtype='<U11')

In [5]:
np.array([1,2,3,4,5,6.0]) 

array([1., 2., 3., 4., 5., 6.])

In [6]:
np.array([[1,3],[3,4]]) # 2-D Array

array([[1, 3],
       [3, 4]])

In [7]:
np.array([[1,3],[3,4],[6,7]])

array([[1, 3],
       [3, 4],
       [6, 7]])

In [8]:
np.array([[1,3],[3,4],[6,7,8]]) 

c:\users\todays\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  """Entry point for launching an IPython kernel.


array([list([1, 3]), list([3, 4]), list([6, 7, 8])], dtype=object)

In [9]:
np.array([[[1,3],[3,4]], [[1,3],[3,4]]]) # 3-D Array

array([[[1, 3],
        [3, 4]],

       [[1, 3],
        [3, 4]]])

#### converting array from 1-d to n-d

In [10]:
np.array([1,2,3], ndmin = 3) # make 3-d data

array([[[1, 2, 3]]])

In [11]:
np.array([1,2,3], ndmin = 2)  # make 1-d data

array([[1, 2, 3]])

#### convert array into complex numbers

In [12]:
np.array([1,2,3] , dtype = complex)  # imaginary part is zero

array([1.+0.j, 2.+0.j, 3.+0.j])

#### we can store the array in the tuple also.

In [13]:
np.array([(1,2), (4,5)]) # 2-d array

array([[1, 2],
       [4, 5]])

#### different data-types

In [14]:
arr = np.array([(1,2), (4,5)] ,dtype = [("a", '<i2'), ('b','<i8')])       # i = 8

In [15]:
arr 

array([(1, 2), (4, 5)], dtype=[('a', '<i2'), ('b', '<i8')])

In [16]:
type(arr[0][0]) 

numpy.int16

In [17]:
type(arr[0][1]) 

numpy.int64

###### -------------------------------------------------------------------------------------------

In [18]:
arr = np.array([[1,3],[3,4]]) 

In [19]:
arr 

array([[1, 3],
       [3, 4]])

In [20]:
type(arr[0][1]) 

numpy.int32

#### ---------------------------------------------------------------------

### Matrix 

#### remember that matrix is the subset of array.

In [21]:
# proof
issubclass(np.matrix, np.ndarray) 

True

In [22]:
#proof
issubclass(np.ndarray , np.matrix) 

False

In [23]:
np.mat(arr) 

matrix([[1, 3],
        [3, 4]])

In [24]:
np.matrix(arr) 

matrix([[1, 3],
        [3, 4]])

#### converting list into array,

In [25]:
l = [1,2,3,4,5] 

In [26]:
np.array(l) 

array([1, 2, 3, 4, 5])

In [27]:
np.asarray(l) 

array([1, 2, 3, 4, 5])

In [28]:
np.asanyarray(l) 

array([1, 2, 3, 4, 5])

#### ----------------------------------

In [29]:
## asanyarray is some what different from asarray and array function.
## output is same but input is somewhat different.

In [30]:
mat = np.matrix(arr) 

In [31]:
np.asanyarray(mat) 

matrix([[1, 3],
        [3, 4]])

In [32]:
#### if the data set is present in any form of array(or matrix) it will not convert it. 

#### ----------------------------------------------

In [33]:
np.asarray(mat)  ## lekin yeh change kar dega bhai. 

array([[1, 3],
       [3, 4]])

#### deep - copy and shallow copy 

In [34]:
arr 

array([[1, 3],
       [3, 4]])

In [35]:
a = arr  # shallowcopy and deep copy

In [36]:
b = np.copy(arr) 

In [37]:
arr[0][0] = 67 

In [38]:
arr 

array([[67,  3],
       [ 3,  4]])

In [39]:
a 

array([[67,  3],
       [ 3,  4]])

In [40]:
b                                      

array([[1, 3],
       [3, 4]])

remember that array objects are mutable

In [41]:
arr[0:10] 

array([[67,  3],
       [ 3,  4]])

In [42]:
arr[-1] 

array([3, 4])

In [43]:
for i in arr:
    print(i) 

[67  3]
[3 4]


#### from function, it take all the function(functions or lambda functions.)

In [44]:
np.fromfunction(lambda i, j :i ==j, (4,4)) 

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [45]:
np.fromfunction(lambda i, j :i *j, (4,4))

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

In [46]:
np.fromfunction(lambda i, j :i /j, (3,3)) ## numpy handles all the error (1/0 or 0/1)

c:\users\todays\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
c:\users\todays\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[nan, 0. , 0. ],
       [inf, 1. , 0.5],
       [inf, 2. , 1. ]])

#### Generator and list comprehension.

In [47]:
[i * i for i in range (5)]   ## list comprehension

[0, 1, 4, 9, 16]

In [48]:
(i * i for i in range (5))  ## generartor 

<generator object <genexpr> at 0x00000000062A0F48>

In [49]:
def test(x):       ## it is also a generator
    yield x 

In [50]:
test(5) 

<generator object test at 0x000000000628D648>

#### to iter from Generator functions

In [51]:
gen = (i * i for i in range (5))

In [52]:
gen 

<generator object <genexpr> at 0x000000000628D9C8>

In [53]:
np.fromiter(gen, dtype = int) 

array([ 0,  1,  4,  9, 16])

In [54]:
np.fromiter(gen, dtype = int)              # function ab khali ho gya hai

array([], dtype=int32)

#### Remember that range function is also an generator funcions. 

In [55]:
np.fromiter(range(5), dtype = int)

array([0, 1, 2, 3, 4])

#### for loops 

In [56]:
gen1 = (i * i for i in range (5))

In [57]:
gen1 

<generator object <genexpr> at 0x00000000062ABB48>

In [58]:
for i in gen1:
    print(i)  

0
1
4
9
16


#### from string functiion 

In [59]:
np.fromstring('1,2,3,5,5' , sep = ',' , dtype = int) 

array([1, 2, 3, 5, 5])

In [60]:
np.fromstring("123 456 789", sep = ' ') 

array([123., 456., 789.])

In [61]:
np.fromstring("123 456 789", sep = ' ', dtype = complex) 

array([123.+0.j, 456.+0.j, 789.+0.j])

In [62]:
#### The objective till we coded till above is to generate a nd array.

In [63]:
l = [3,4,5,6,7,8] 

In [64]:
arr = np.array(l) 

In [65]:
arr 

array([3, 4, 5, 6, 7, 8])

In [66]:
type(arr) 

numpy.ndarray

In [67]:
arr1 = [[1,2,3,4], [2,3,4,5], [4,5,6,7]] 

In [68]:
arr1 

[[1, 2, 3, 4], [2, 3, 4, 5], [4, 5, 6, 7]]

In [69]:
type(arr1) 

list

In [70]:
arr1 = np.array([[1,2,3,4], [2,3,4,5], [4,5,6,7]])

In [71]:
arr1 

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [4, 5, 6, 7]])

In [72]:
## dimension of array
arr1.ndim 

2

In [73]:
arr.shape 

(6,)

In [74]:
arr1.shape 

(3, 4)

In [75]:
arr1.size 

12

In [76]:
arr1.dtype 

dtype('int32')

In [77]:
arr 

array([3, 4, 5, 6, 7, 8])

In [78]:
arr.size 

6

In [79]:
arr.shape 

(6,)

In [80]:
arr.ndim 

1

In [81]:
arr2 = np.array([[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]]]) 

In [82]:
arr2 

array([[[1, 2, 3, 4],
        [4, 5, 6, 7]],

       [[1, 2, 3, 4],
        [4, 5, 6, 7]]])

In [83]:
arr2.size 

16

In [84]:
# we have 2 no. of data with dimension(2,4) 
arr2.shape 

(2, 2, 4)

In [85]:
arr2.ndim 

3

In [86]:
arr4 = np.array([[[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]]]]) 

In [87]:
arr4  

array([[[[1, 2, 3, 4],
         [4, 5, 6, 7]],

        [[1, 2, 3, 4],
         [4, 5, 6, 7]],

        [[1, 2, 3, 4],
         [4, 5, 6, 7]],

        [[1, 2, 3, 4],
         [4, 5, 6, 7]]]])

In [88]:
arr4.ndim 

4

In [89]:
# we have (2 X 4) 4 matrixes in a single 1.
arr4.shape 

(1, 4, 2, 4)

#### range 

In [90]:
range(5)  # range function do not take any floating point number.

range(0, 5)

In [91]:
list(range(5)) 

[0, 1, 2, 3, 4]

In [92]:
np.arange(5) 

array([0, 1, 2, 3, 4])

In [93]:
np.arange(6.6) 

array([0., 1., 2., 3., 4., 5., 6.])

In [94]:
np.arange(6.6,20, 2.2) # 6.6 to 20.0 and with 2.2 jump  

array([ 6.6,  8.8, 11. , 13.2, 15.4, 17.6, 19.8])

In [95]:
np.arange(9,6.6, -.3) # upper bound value(6.6) bhi aa rha hai means np.arange can give floating point
                      # upper value but not integer ka uper value np.arange nhi dega.

array([9. , 8.7, 8.4, 8.1, 7.8, 7.5, 7.2, 6.9, 6.6])

#### linspace

In [96]:
np.linspace(3,8) 

array([3.        , 3.10204082, 3.20408163, 3.30612245, 3.40816327,
       3.51020408, 3.6122449 , 3.71428571, 3.81632653, 3.91836735,
       4.02040816, 4.12244898, 4.2244898 , 4.32653061, 4.42857143,
       4.53061224, 4.63265306, 4.73469388, 4.83673469, 4.93877551,
       5.04081633, 5.14285714, 5.24489796, 5.34693878, 5.44897959,
       5.55102041, 5.65306122, 5.75510204, 5.85714286, 5.95918367,
       6.06122449, 6.16326531, 6.26530612, 6.36734694, 6.46938776,
       6.57142857, 6.67346939, 6.7755102 , 6.87755102, 6.97959184,
       7.08163265, 7.18367347, 7.28571429, 7.3877551 , 7.48979592,
       7.59183673, 7.69387755, 7.79591837, 7.89795918, 8.        ])

In [97]:
np.linspace(3,8,5) 

array([3.  , 4.25, 5.5 , 6.75, 8.  ])

In [98]:
np.zeros(5) 

array([0., 0., 0., 0., 0.])

In [99]:
np.zeros((2,5)) 

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [100]:
np.zeros((2,5,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [101]:
# we have (5 x 1)  4 data in 2 arrays 

np.zeros((2,5,4,1)) 

array([[[[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]]],


       [[[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]]]])

In [102]:
np.ones(4) 

array([1., 1., 1., 1.])

In [103]:
np.ones((2,3,1))

array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]])

In [104]:
np.ones((2,3,1))+5 

array([[[6.],
        [6.],
        [6.]],

       [[6.],
        [6.],
        [6.]]])

#### np.empty() 

In [105]:
np.empty((3,4)) 

array([[2.87e-322, 0.00e+000, 0.00e+000, 0.00e+000],
       [0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000],
       [0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000]])

In [106]:
np.empty(5) 

array([0., 0., 0., 0., 0.])

#### np.eye() 

In [107]:
#### Identity Matrixes

np.eye(3)      #it means (3 x 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [108]:
np.linspace(2,4,4)     # it is considerng the endpoint

array([2.        , 2.66666667, 3.33333333, 4.        ])

In [109]:
np.linspace(2,4,4, endpoint=False) 

array([2. , 2.5, 3. , 3.5])

In [110]:
np.linspace(2,4,4, endpoint=False, axis = 0) 

array([2. , 2.5, 3. , 3.5])

In [111]:
# array passed here
np.linspace([2,4],4, endpoint=False, axis = 0)

array([[2.  , 4.  ],
       [2.04, 4.  ],
       [2.08, 4.  ],
       [2.12, 4.  ],
       [2.16, 4.  ],
       [2.2 , 4.  ],
       [2.24, 4.  ],
       [2.28, 4.  ],
       [2.32, 4.  ],
       [2.36, 4.  ],
       [2.4 , 4.  ],
       [2.44, 4.  ],
       [2.48, 4.  ],
       [2.52, 4.  ],
       [2.56, 4.  ],
       [2.6 , 4.  ],
       [2.64, 4.  ],
       [2.68, 4.  ],
       [2.72, 4.  ],
       [2.76, 4.  ],
       [2.8 , 4.  ],
       [2.84, 4.  ],
       [2.88, 4.  ],
       [2.92, 4.  ],
       [2.96, 4.  ],
       [3.  , 4.  ],
       [3.04, 4.  ],
       [3.08, 4.  ],
       [3.12, 4.  ],
       [3.16, 4.  ],
       [3.2 , 4.  ],
       [3.24, 4.  ],
       [3.28, 4.  ],
       [3.32, 4.  ],
       [3.36, 4.  ],
       [3.4 , 4.  ],
       [3.44, 4.  ],
       [3.48, 4.  ],
       [3.52, 4.  ],
       [3.56, 4.  ],
       [3.6 , 4.  ],
       [3.64, 4.  ],
       [3.68, 4.  ],
       [3.72, 4.  ],
       [3.76, 4.  ],
       [3.8 , 4.  ],
       [3.84, 4.  ],
       [3.88,

In [112]:
np.linspace([2,4],4, endpoint=False, axis = 1) 

array([[2.  , 2.04, 2.08, 2.12, 2.16, 2.2 , 2.24, 2.28, 2.32, 2.36, 2.4 ,
        2.44, 2.48, 2.52, 2.56, 2.6 , 2.64, 2.68, 2.72, 2.76, 2.8 , 2.84,
        2.88, 2.92, 2.96, 3.  , 3.04, 3.08, 3.12, 3.16, 3.2 , 3.24, 3.28,
        3.32, 3.36, 3.4 , 3.44, 3.48, 3.52, 3.56, 3.6 , 3.64, 3.68, 3.72,
        3.76, 3.8 , 3.84, 3.88, 3.92, 3.96],
       [4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  ,
        4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  ,
        4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  ,
        4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  , 4.  ,
        4.  , 4.  , 4.  , 4.  , 4.  , 4.  ]])

#### logspace

In [113]:
np.logspace([2],[3] , axis = 0)    # it gives data on the logscale

array([[ 100.        ],
       [ 104.81131342],
       [ 109.8541142 ],
       [ 115.13953993],
       [ 120.67926406],
       [ 126.48552169],
       [ 132.57113656],
       [ 138.94954944],
       [ 145.63484775],
       [ 152.64179672],
       [ 159.98587196],
       [ 167.68329368],
       [ 175.75106249],
       [ 184.20699693],
       [ 193.06977289],
       [ 202.35896477],
       [ 212.09508879],
       [ 222.29964825],
       [ 232.99518105],
       [ 244.20530945],
       [ 255.95479227],
       [ 268.26957953],
       [ 281.1768698 ],
       [ 294.70517026],
       [ 308.88435965],
       [ 323.74575428],
       [ 339.32217719],
       [ 355.64803062],
       [ 372.75937203],
       [ 390.69399371],
       [ 409.49150624],
       [ 429.19342601],
       [ 449.8432669 ],
       [ 471.48663635],
       [ 494.17133613],
       [ 517.94746792],
       [ 542.86754393],
       [ 568.9866029 ],
       [ 596.36233166],
       [ 625.05519253],
       [ 655.12855686],
       [ 686.648

In [114]:
np.logspace(2,3, 5) 

array([ 100.        ,  177.827941  ,  316.22776602,  562.34132519,
       1000.        ])

In [115]:
np.logspace([2,3],4 , axis = 1) 

array([[  100.        ,   109.8541142 ,   120.67926406,   132.57113656,
          145.63484775,   159.98587196,   175.75106249,   193.06977289,
          212.09508879,   232.99518105,   255.95479227,   281.1768698 ,
          308.88435965,   339.32217719,   372.75937203,   409.49150624,
          449.8432669 ,   494.17133613,   542.86754393,   596.36233166,
          655.12855686,   719.685673  ,   790.60432109,   868.51137375,
          954.09547635,  1048.11313415,  1151.39539933,  1264.85521686,
         1389.49549437,  1526.41796718,  1676.83293681,  1842.06996933,
         2023.58964773,  2222.99648253,  2442.05309455,  2682.69579528,
         2947.05170255,  3237.45754282,  3556.48030622,  3906.93993705,
         4291.93426013,  4714.86636346,  5179.47467923,  5689.86602902,
         6250.55192527,  6866.48845004,  7543.12006335,  8286.42772855,
         9102.98177992, 10000.        ],
       [ 1000.        ,  1048.11313415,  1098.54114199,  1151.39539933,
         1206.79264064,

In [116]:
np.logspace([2,3],4 , axis = 0)  

array([[  100.        ,  1000.        ],
       [  109.8541142 ,  1048.11313415],
       [  120.67926406,  1098.54114199],
       [  132.57113656,  1151.39539933],
       [  145.63484775,  1206.79264064],
       [  159.98587196,  1264.85521686],
       [  175.75106249,  1325.71136559],
       [  193.06977289,  1389.49549437],
       [  212.09508879,  1456.3484775 ],
       [  232.99518105,  1526.41796718],
       [  255.95479227,  1599.85871961],
       [  281.1768698 ,  1676.83293681],
       [  308.88435965,  1757.51062485],
       [  339.32217719,  1842.06996933],
       [  372.75937203,  1930.69772888],
       [  409.49150624,  2023.58964773],
       [  449.8432669 ,  2120.95088792],
       [  494.17133613,  2222.99648253],
       [  542.86754393,  2329.95181052],
       [  596.36233166,  2442.05309455],
       [  655.12855686,  2559.5479227 ],
       [  719.685673  ,  2682.69579528],
       [  790.60432109,  2811.76869797],
       [  868.51137375,  2947.05170255],
       [  954.09

In [117]:
np.logspace([2],[3], axis = 1) 

array([[ 100.        ,  104.81131342,  109.8541142 ,  115.13953993,
         120.67926406,  126.48552169,  132.57113656,  138.94954944,
         145.63484775,  152.64179672,  159.98587196,  167.68329368,
         175.75106249,  184.20699693,  193.06977289,  202.35896477,
         212.09508879,  222.29964825,  232.99518105,  244.20530945,
         255.95479227,  268.26957953,  281.1768698 ,  294.70517026,
         308.88435965,  323.74575428,  339.32217719,  355.64803062,
         372.75937203,  390.69399371,  409.49150624,  429.19342601,
         449.8432669 ,  471.48663635,  494.17133613,  517.94746792,
         542.86754393,  568.9866029 ,  596.36233166,  625.05519253,
         655.12855686,  686.648845  ,  719.685673  ,  754.31200634,
         790.60432109,  828.64277285,  868.51137375,  910.29817799,
         954.09547635, 1000.        ]])

In [118]:
np.logspace([2],[3], axis = 0) 

array([[ 100.        ],
       [ 104.81131342],
       [ 109.8541142 ],
       [ 115.13953993],
       [ 120.67926406],
       [ 126.48552169],
       [ 132.57113656],
       [ 138.94954944],
       [ 145.63484775],
       [ 152.64179672],
       [ 159.98587196],
       [ 167.68329368],
       [ 175.75106249],
       [ 184.20699693],
       [ 193.06977289],
       [ 202.35896477],
       [ 212.09508879],
       [ 222.29964825],
       [ 232.99518105],
       [ 244.20530945],
       [ 255.95479227],
       [ 268.26957953],
       [ 281.1768698 ],
       [ 294.70517026],
       [ 308.88435965],
       [ 323.74575428],
       [ 339.32217719],
       [ 355.64803062],
       [ 372.75937203],
       [ 390.69399371],
       [ 409.49150624],
       [ 429.19342601],
       [ 449.8432669 ],
       [ 471.48663635],
       [ 494.17133613],
       [ 517.94746792],
       [ 542.86754393],
       [ 568.9866029 ],
       [ 596.36233166],
       [ 625.05519253],
       [ 655.12855686],
       [ 686.648

In [119]:
d = np.linspace(4,7,40) 

In [120]:
d  

array([4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
       4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
       4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
       5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846,
       5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
       5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
       6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
       6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ])

In [121]:
d.shape

(40,)

In [122]:
d.ndim 

1

### reshape

In [123]:
d.reshape

<function ndarray.reshape>

In [124]:
d.reshape(40,1) 

array([[4.        ],
       [4.07692308],
       [4.15384615],
       [4.23076923],
       [4.30769231],
       [4.38461538],
       [4.46153846],
       [4.53846154],
       [4.61538462],
       [4.69230769],
       [4.76923077],
       [4.84615385],
       [4.92307692],
       [5.        ],
       [5.07692308],
       [5.15384615],
       [5.23076923],
       [5.30769231],
       [5.38461538],
       [5.46153846],
       [5.53846154],
       [5.61538462],
       [5.69230769],
       [5.76923077],
       [5.84615385],
       [5.92307692],
       [6.        ],
       [6.07692308],
       [6.15384615],
       [6.23076923],
       [6.30769231],
       [6.38461538],
       [6.46153846],
       [6.53846154],
       [6.61538462],
       [6.69230769],
       [6.76923077],
       [6.84615385],
       [6.92307692],
       [7.        ]])

In [125]:
d.reshape(1,2,20)

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
         4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
         4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
         5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846],
        [5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
         5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
         6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
         6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [126]:
d.reshape(2,1,20)

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
         4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
         4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
         5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846]],

       [[5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
         5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
         6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
         6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [127]:
d.reshape(1,2,1,20)

array([[[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
          4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
          4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
          5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846]],

        [[5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
          5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
          6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
          6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]]])

#### Generating Random data

In [128]:
## Gaussian Distribution data (mean and S.D. can be anything)

np.random.rand(3) 

array([0.60032898, 0.37233399, 0.30791623])

In [129]:
# standard Normal Distribution (mean is zero, s.d. = 0)

np.random.randn(5) 

array([ 1.17142448, -0.46952024,  0.51370209, -1.37499805,  1.25504991])

In [130]:
np.random.randn(2,3) 

array([[-0.28705239,  0.81717174, -0.94015461],
       [ 0.0816073 , -0.75209738,  0.21384468]])

In [131]:
np.random.randn(2,2,3) 

array([[[ 0.03113807, -0.04051147, -0.14635572],
        [ 0.82584323,  0.28062245,  1.93879457]],

       [[ 0.46197305, -1.81067022,  1.66903576],
        [ 0.38996017, -1.00113199,  0.68889496]]])

In [132]:
np.random.randint(5,60) 

14

In [133]:
np.random.randint(5,60) 

11

In [134]:
np.random.randint(5,60, (4,4))  # 4 X 4 Matrixes , data should be randomly from (5,60)

array([[28, 36, 59, 57],
       [32, 27, 21, 34],
       [48, 22, 56, 23],
       [ 7, 15, 22, 50]])

In [135]:
np.random.randn(2,2,3)

array([[[-0.61427731,  0.93016525, -0.75931087],
        [-0.77424199, -1.64931062,  0.3245784 ]],

       [[-1.18809737, -0.85250061, -1.05862996],
        [ 1.63185806,  1.13852914, -0.92822403]]])

In [136]:
arr = np.random.randint(3,9, ( 3,3)) 

In [137]:
arr 

array([[6, 5, 7],
       [6, 4, 8],
       [6, 8, 7]])

In [138]:
arr.reshape(1,9)   # 1 row 9 column 

array([[6, 5, 7, 6, 4, 8, 6, 8, 7]])

In [139]:
arr.reshape(9,1)  # 1 row 9 column 

array([[6],
       [5],
       [7],
       [6],
       [4],
       [8],
       [6],
       [8],
       [7]])

In [140]:
arr.reshape(1,1,9)  # 3-d data 

array([[[6, 5, 7, 6, 4, 8, 6, 8, 7]]])

In [141]:
arr.reshape(3,3,1)  ## 3 matrixes of (3,1)

array([[[6],
        [5],
        [7]],

       [[6],
        [4],
        [8]],

       [[6],
        [8],
        [7]]])

In [142]:
arr.reshape(3, -1) ## agar hum 3 ke saath koi bhi ek negative no. daalege toh woh automatically detect
                 ## kar lenga ki dusra factor kya aana chahiye chahiye, yaha pr woh (3 x 3) le rha hai

array([[6, 5, 7],
       [6, 4, 8],
       [6, 8, 7]])

In [143]:
arr.reshape(3, -11214632314) 

array([[6, 5, 7],
       [6, 4, 8],
       [6, 8, 7]])

In [144]:
arr.reshape(3,3) 

array([[6, 5, 7],
       [6, 4, 8],
       [6, 8, 7]])

In [145]:
arr 

array([[6, 5, 7],
       [6, 4, 8],
       [6, 8, 7]])

In [146]:
arr.max() 

8

In [147]:
arr.min() 

4

#### sclicing in form of array

In [148]:
arr = np.random.randint(4,100, (5,5)) 

In [149]:
arr 

array([[86, 26, 37,  7, 53],
       [99, 87, 75, 33, 69],
       [67, 36, 35, 49, 37],
       [80, 11, 22, 78, 19],
       [80, 78, 55, 57, 39]])

In [150]:
arr [3: ,3: ] 

array([[78, 19],
       [57, 39]])

In [151]:
arr[: , 1:4:2]       # puri ki puri column no.1 & 3 print kar do   

array([[26,  7],
       [87, 33],
       [36, 49],
       [11, 78],
       [78, 57]])

In [152]:
arr[: ,[1,3]] 

array([[26,  7],
       [87, 33],
       [36, 49],
       [11, 78],
       [78, 57]])

In [153]:
arr>10 

array([[ True,  True,  True, False,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [154]:
arr[arr>10] 

array([86, 26, 37, 53, 99, 87, 75, 33, 69, 67, 36, 35, 49, 37, 80, 11, 22,
       78, 19, 80, 78, 55, 57, 39])

#### Matrixes 

In [155]:
arr 

array([[86, 26, 37,  7, 53],
       [99, 87, 75, 33, 69],
       [67, 36, 35, 49, 37],
       [80, 11, 22, 78, 19],
       [80, 78, 55, 57, 39]])

In [156]:
arr * arr       # dimension should always equal to do the multiplication of array

array([[7396,  676, 1369,   49, 2809],
       [9801, 7569, 5625, 1089, 4761],
       [4489, 1296, 1225, 2401, 1369],
       [6400,  121,  484, 6084,  361],
       [6400, 6084, 3025, 3249, 1521]])

In [157]:
arr1 = np.random.randint(2,4,(3,3)) 

In [158]:
arr2 = np.random.randint(2,4,(3,3)) 

In [159]:
arr1 

array([[3, 2, 2],
       [2, 3, 3],
       [2, 3, 3]])

In [160]:
arr2 

array([[3, 2, 2],
       [2, 2, 3],
       [2, 2, 2]])

In [161]:
arr1 * arr2 

array([[9, 4, 4],
       [4, 6, 9],
       [4, 6, 6]])

#### Matrix multiplication 

In [162]:
arr1 @ arr2 

array([[17, 14, 16],
       [18, 16, 19],
       [18, 16, 19]])

#### infinity 

In [163]:
arr/ 0 

c:\users\todays\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf]])

In [164]:
arr **2     #square

array([[7396,  676, 1369,   49, 2809],
       [9801, 7569, 5625, 1089, 4761],
       [4489, 1296, 1225, 2401, 1369],
       [6400,  121,  484, 6084,  361],
       [6400, 6084, 3025, 3249, 1521]], dtype=int32)

### BroadCasting 

In [165]:
arr = np.zeros((3,4)) 

In [166]:
arr 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [167]:
a = np.array([1,2,3,5]) 

In [168]:
a 

array([1, 2, 3, 5])

#### row wise Broadcasting 

In [169]:
arr + a 

array([[1., 2., 3., 5.],
       [1., 2., 3., 5.],
       [1., 2., 3., 5.]])

In [170]:
arr + 5 

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

#### Column wise Broadcasting

In [171]:
b = np.array([5,6,7]) 

In [172]:
b 

array([5, 6, 7])

In [173]:
b.reshape(3,1) 

array([[5],
       [6],
       [7]])

In [174]:
arr + b.reshape(3,1) 

array([[5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [175]:
b 

array([5, 6, 7])

In [176]:
b.T         # transpose did not work here, becoz it only works on 2-d

array([5, 6, 7])

In [177]:
b = np.array([[5,6,7]]) 

In [178]:
b 

array([[5, 6, 7]])

In [179]:
b.T 

array([[5],
       [6],
       [7]])

In [180]:
arr + b.T 

array([[5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

#### square root 

In [181]:
arr = np.random.rand(5,4) 

In [182]:
arr 

array([[0.46949213, 0.19152621, 0.90674509, 0.94541988],
       [0.82239736, 0.16453519, 0.43204077, 0.4308228 ],
       [0.40762423, 0.27950892, 0.72147749, 0.71551583],
       [0.58261528, 0.39989063, 0.26989646, 0.9481202 ],
       [0.96391346, 0.22310104, 0.31415086, 0.40965969]])

In [183]:
np.sqrt(arr) 

array([[0.68519496, 0.43763708, 0.95223164, 0.97232704],
       [0.90686127, 0.40562938, 0.65729808, 0.65637093],
       [0.63845456, 0.52868603, 0.84939831, 0.84588169],
       [0.76329239, 0.63236906, 0.5195156 , 0.97371464],
       [0.98179095, 0.47233573, 0.56049163, 0.64004663]])

#### exponential 

In [184]:
np.exp(arr) 

array([[1.59918182, 1.21109658, 2.47624944, 2.57389387],
       [2.27594957, 1.17884506, 1.54039791, 1.53852289],
       [1.50324218, 1.32248021, 2.05747086, 2.04524141],
       [1.79071553, 1.49166155, 1.30982882, 2.58085362],
       [2.62193728, 1.24994686, 1.36909627, 1.50630509]])

#### Log 

In [185]:
np.log10(arr) 

array([[-0.32837168, -0.71777178, -0.04251479, -0.02437527],
       [-0.08491829, -0.78374119, -0.36447527, -0.36570133],
       [-0.38974001, -0.55360433, -0.14177722, -0.14538075],
       [-0.23461813, -0.39805877, -0.56880282, -0.0231366 ],
       [-0.01596195, -0.65149841, -0.50286174, -0.38757677]])

In [186]:
arr1 = np.random.randint(2,5, (5,5)) 

In [187]:
arr1 

array([[4, 2, 4, 2, 2],
       [4, 2, 4, 3, 3],
       [3, 2, 4, 3, 2],
       [2, 2, 2, 4, 3],
       [2, 4, 4, 2, 3]])

In [188]:
np.log10(arr1)

array([[0.60205999, 0.30103   , 0.60205999, 0.30103   , 0.30103   ],
       [0.60205999, 0.30103   , 0.60205999, 0.47712125, 0.47712125],
       [0.47712125, 0.30103   , 0.60205999, 0.47712125, 0.30103   ],
       [0.30103   , 0.30103   , 0.30103   , 0.60205999, 0.47712125],
       [0.30103   , 0.60205999, 0.60205999, 0.30103   , 0.47712125]])

In [189]:
np.log2(arr1)

array([[2.       , 1.       , 2.       , 1.       , 1.       ],
       [2.       , 1.       , 2.       , 1.5849625, 1.5849625],
       [1.5849625, 1.       , 2.       , 1.5849625, 1.       ],
       [1.       , 1.       , 1.       , 2.       , 1.5849625],
       [1.       , 2.       , 2.       , 1.       , 1.5849625]])

### Seed

In [190]:
np.random.seed(13)
np.random.rand(2,4) 

array([[0.77770241, 0.23754122, 0.82427853, 0.9657492 ],
       [0.97260111, 0.45344925, 0.60904246, 0.77552651]])

#### ab jo log bhi seed ko 13 karke set karenge toh sabko ek jaisa random data milega bhai. 